export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const DELETE_CONVERSATION = "DELETE_CONVERSATION";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const GET_CONVERSATION = "GET_CONVERSATION";
export const GET_MESSAGE = "GET_MESSAGE";
export const SET_CURRENT_CONVERSATION = "SET_CURRENT_CONVERSATION";
export const GET_MORE_MESSAGES = "GET_MORE_MESSAGES";
