export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const DELETE_ALL_NOTIFICATIONS = "DELETE_ALL_NOTIFICATIONS";
export const CHANGE_NOTIFY_ON = "CHANGE_NOTIFY_ON";
export const UPDATE_NOTIFY = "UPDATE_NOTIFY";
export const CHANGE_IS_READ = "CHANGE_IS_READ";
